# Site Configuration
title: Hacker Adam
description: I'm Adam. I Hack Stuff.  
url: http://hackeradam.com
baseurl: ""

# Author Configuration
author:
  name: 'Adam Thompson'
  url:  https://serialphotog.com

# Pagination Amount
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

timezone: America/New_York

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

compress_html:
  clippings: all
  comments: all
  profile: false

sass:
    style: compressed
