# Site Configuration
title: Musings of a Hacker
description: The technical adventures of Adam Thompson
url: http://serialphotog.github.io
baseurl: ""

# Author Configuration
author:
  name: 'Adam Thompson'
  url:  https://serialphotog.com

# Pagination Amount
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/19210192?v=3&s=460 #https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

timezone: America/New_York

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
